baseURL = 'https://notcaste.com/'
languageCode = 'es-us'
title = 'NotCaste'

enableEmoji = true

[permalinks]
    blog = "/:slug"

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 10

[[menus.main]]
name = 'Projects'
pageRef = '/#'
weight = 15

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 20

[[menus.social]]
name = 'GitHub'
pre = 'github'
url = 'https://github.com/casteindex'
weight = 10

[[menus.social]]
name = 'Letterboxd'
pre = 'letterboxd'
url = 'https://letterboxd.com/caste_alejandro/'
weight = 20

[[menus.social]]
name = 'RSS Feed'
pre = 'rss'
url = '/index.xml'
weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    style = 'catppuccin-macchiato'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

